### ISSUE TITLE
If you scroll down then exit, this doesn't work

### ISSUE THREAD

**Issue by earthlingworks** [flaviovs/jquery.exitintent#1]
Basically, if I don't scroll and exit from the top, it works great. But on a longer page, if I scroll down a bit then it no longer works. Might have to do with it being bound to the document instead of the viewport? Unsure.

**Comment by klaasnotfound** [comment]
Yep, noticed the same thing.
This is easily fixed by using `clientY` instead of `pageY` on [line 5](https://github.com/flaviovs/jquery.exitintent/blob/master/jquery.exitintent.js#L5).

**Comment by flaviovs** [comment]
Firstly I apologize for taking too long to respond, and thank you for reporting and following up with this issue.

Yep, the problem was there. I just committed a fix based on the solution above (thanks @klaasnotfound!)
