### ISSUE TITLE
Uncaught TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.combineReducers) is not a function 

### ISSUE THREAD

**Issue by vishambardutt** [flaviovs/jquery.exitintent#4]
Hi, Guys i am new in react-redux having some issue during creating a project . I am getting following error but  am unable to resove issue. Kindly check what is happening.

please check  files

 https://github.com/vishambardutt/react-reduxCart.git

thanx in advance.

![image](https://user-images.githubusercontent.com/62166264/199321455-0c5998f2-0037-4644-b72e-6e7afb6a85a3.png)

**Comment by flaviovs** [comment]
Wrong project.
